apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alerts.yaml: |
    groups:
    - name: solace-alerts
      rules:

      - alert: HighQueueLag
        expr: solace_message_lag > 500
        for: 1m
        labels:
          severity: critical
        annotations:
          description: Message queue lag too high

      - alert: ConsumerDown
        expr: up{job="solace-consumer"} == 0
        for: 30s
        labels:
          severity: critical
